### ISSUE TITLE
Add support for Linux (patch included)

### ISSUE THREAD

**Issue by afarah1** [mfkp/tinderplusplus#28]
Hi. Take a look at this commit:

https://github.com/afarah1/tinderplusplus/commit/615e862609c44e0540a1bdd7ff89f1fb481fae86

You can run it on Linux (native) with these adaptations. I know nothing about nodejs and npm and had to play around with your app for a while until I got it working, the instructions you provided are far from sufficient. There's probably a better way to install those dependencies and whatnot btw.

**Comment by pedroapero** [comment]
You saved me a lot of time, thanks!

I also had to install the following packets with Apt (although they may be already installed in a full-featured desktop Linux environment):
libnss3
libpangocairo-1.0-0
libxi6
libxcomposite1
libasound2
libxdamage1
libxtst6
libxrandr2
libcap2
libudev0
libgtk2.0-0
libnotify4

Cheers

**Comment by SalahAdDin** [comment]
I have this error:
```
node build.js
Before running, make sure versions are updated in both package.json and desktop-app/package.json
/home/salahaddin/tinderplusplus/node_modules/graceful-ncp/node_modules/proxyquire/lib/proxyquire.js:13
    if (!mdl[key])  mdl[key] = original[key];
                             ^

TypeError: Cannot assign to read only property 'F_OK' of #<Object>
    at /home/salahaddin/tinderplusplus/node_modules/graceful-ncp/node_modules/proxyquire/lib/proxyquire.js:13:30
    at Array.forEach (native)
    at fillMissingKeys (/home/salahaddin/tinderplusplus/node_modules/graceful-ncp/node_modules/proxyquire/lib/proxyquire.js:12:25)
    at Proxyquire._require (/home/salahaddin/tinderplusplus/node_modules/graceful-ncp/node_modules/proxyquire/lib/proxyquire.js:143:7)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/salahaddin/tinderplusplus/node_modules/ncp/lib/ncp.js:1:72)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) (/home/salahaddin/tinderplusplus/node_modules/graceful-ncp/node_modules/proxyquire/lib/proxyquire.js:235:43)
    at Module.load (module.js:357:32)
```
